[project]
name = "taskflow-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "vishaalx", email = "contact.vishaalx@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
taskflow-cli = "taskflow_cli:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
